import {K2D} from "next/font/google";
import AuthProvider from "./AuthProvider";

const k2d = K2D({ subsets: ["latin"],weight:["300","400","500","600","700"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function QuizLayout({ children }) {  
  return (
    <html lang="en">
       <AuthProvider>
        <body className={`${k2d.className}`}>{children}</body>
       </AuthProvider>
    </html>
  );
}
